spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/embeded_db

server:
  port: 8091

jenkins:
  skip: false
  url: http://ec2-52-81-45-194.cn-north-1.compute.amazonaws.com.cn:8088/job/mock-server/build?token=ThisIsAToken