---
- hosts: aws
  remote_user: ubuntu
  tasks:
  - name: pull image
    command: docker pull "{{image}}:{{tag}}"
    become: true
  - name: stop old container
    command: docker stop "contract-listener"
    become: true
  - name: remove old container
    command: docker rm "contract-listener"
    become: true
  - name: start new service container
    command: docker run -d -p "8090:8090" --name "contract-listener" {{image}}:{{tag}}
    become: true